apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: softwarefactorytenants.softwarefactory.io
spec:
  group: softwarefactory.io
  scope: Namespaced
  names:
    plural: softwarefactorytenants
    singular: softwarefactorytenant
    kind: SoftwareFactoryTenant
    shortNames:
      - sft
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [tenantId, displayName]
              properties:
                tenantId:
                  type: string
                displayName:
                  type: string
                clusterName:
                  type: string
                gitopsRepository:
                  type: string
                isolation:
                  type: object
                  properties:
                    namespace:
                      type: string
                    networkPolicy:
                      type: boolean
